# Generated by Django 2.2 on 2023-04-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000, null=True)),
                ('wordSize', models.IntegerField(max_length=50, null=True)),
                ('score', models.IntegerField(max_length=1, null=True)),
            ],
        ),
    ]
