# Generated by Django 2.2 on 2023-04-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='word',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
